import { z } from "zod";

// Helpers para validação
const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
const cpfRegex = /^\d{3}\.\d{3}\.\d{3}-\d{2}$/;
const phoneRegex = /^\(\d{2}\) \d{4,5}-\d{4}$/;

export const pacienteSchema = z.object({
  data_avaliacao: z.string().regex(dateRegex, "Data inválida").min(1, "Campo obrigatório"),
  nome_completo: z.string().min(3, "Nome muito curto").min(1, "Campo obrigatório"),
  data_nascimento: z.string().regex(dateRegex, "Data inválida").min(1, "Campo obrigatório"),
  idade: z.number().min(0, "Idade inválida").min(1, "Campo obrigatório"),
  naturalidade: z.string().min(2, "Naturalidade inválida").min(1, "Campo obrigatório"),
  religiao: z.string().min(1, "Campo obrigatório"),
  praticante: z.boolean().default(false),
  profissao: z.string().min(1, "Campo obrigatório"),
  escolaridade: z.string().min(1, "Campo obrigatório"),
  estado_civil: z.string().min(1, "Campo obrigatório"),
  cpf: z.string().regex(cpfRegex, "CPF inválido").min(1, "Campo obrigatório"),
  rg: z.string().min(5, "RG inválido").min(1, "Campo obrigatório"),
  orgao_expedidor: z.string().min(1, "Campo obrigatório"),
  nome_pai: z.string().min(1, "Campo obrigatório"),
  nome_mae: z.string().min(1, "Campo obrigatório"),
  data_acolhimento: z.string().regex(dateRegex, "Data inválida").min(1, "Campo obrigatório"),
  responsavel: z.string().min(1, "Campo obrigatório"),
  telefone_responsavel: z.string().regex(phoneRegex, "Telefone inválido").min(1, "Campo obrigatório"),
  rg_responsavel: z.string().min(1, "Campo obrigatório"),
  cpf_responsavel: z.string().min(1, "Campo obrigatório"),
  endereco: z.string().min(5, "Endereço muito curto").min(1, "Campo obrigatório"),
  contato_emergencia: z.string().min(5, "Contato muito curto").min(1, "Campo obrigatório"),
  acolhido_outra_instituicao: z.boolean().default(false),
  tempo_acolhimento_anterior: z.string().optional(),
  possui_convenio: z.boolean().default(false),
  nome_convenio: z.string().optional(),
  tipo_sanguineo: z.string().min(1, "Campo obrigatório"),
  receituario_medico: z.string().min(1, "Campo obrigatório"),
  carteira_vacinacao: z.boolean().default(false),
  situacao_vacinal: z.string().min(1, "Campo obrigatório"),
  vacina_covid_1: z.string().optional(),
  vacina_covid_2: z.string().optional(),
  vacina_covid_3: z.string().optional(),
  vacina_covid_4: z.string().optional(),
  alergias_medicamentosas: z.boolean().default(false),
  quais_alergias: z.string().optional(),
  tabagista: z.boolean().default(false),
  etilista: z.boolean().default(false),
  protese_dentaria: z.boolean().default(false),
  utiliza_fraldas: z.boolean().default(false),
  orientacao_tempo: z.boolean().default(true),
  orientacao_espaco: z.boolean().default(true),
  medicamentos_uso: z.string().optional(),
  grau_dependencia: z.number().min(0).max(3).default(0).nullable(),
  banho: z.string().min(1, "Campo obrigatório"),
  vestir: z.string().min(1, "Campo obrigatório"),
  banheiro: z.string().min(1, "Campo obrigatório"),
  transferencia: z.string().min(1, "Campo obrigatório"),
  continencia: z.string().min(1, "Campo obrigatório"),
  alimentacao: z.string().min(1, "Campo obrigatório"),
  preferencias: z.string().optional(),
  dificuldade_visual: z.boolean().default(false),
  usa_oculos: z.boolean().default(false),
  demencia: z.boolean().default(false),
  tipo_demencia: z.string().optional(),
  comunicacao_verbal: z.boolean().default(true),
  dificuldade_fala: z.boolean().default(false),
  dificuldade_auditiva: z.boolean().default(false),
  protese_auditiva: z.boolean().default(false),
  avc: z.boolean().default(false),
  tce: z.boolean().default(false),
  hipertensao: z.boolean().default(false),
  cardiopatias: z.boolean().default(false),
  quais_cardiopatias: z.string().optional(),
  hipotireoidismo: z.boolean().default(false),
  colesterol_alto: z.boolean().default(false),
  artrose: z.boolean().default(false),
  diabetes: z.boolean().default(false),
  tipo_diabetes: z.string().optional(),
  historico_cancer: z.boolean().default(false),
  tipo_cancer: z.string().optional(),
  osteoporose: z.boolean().default(false),
  fraturas: z.boolean().default(false),
  onde_fraturas: z.string().optional(),
  cirurgia: z.boolean().default(false),
  onde_cirurgia: z.string().optional(),
  depressao: z.boolean().default(false),
  outros_antecedentes: z.string().optional(),
  alimenta_sozinho: z.boolean().default(true),
  tipo_alimentacao: z.string().min(1, "Campo obrigatório"),
  dificuldade_degluticao: z.boolean().default(false),
  engasgos: z.boolean().default(false),
  uso_sonda: z.boolean().default(false),
  tipo_sonda: z.string().optional(),
  alergia_alimento: z.boolean().default(false),
  qual_alimento: z.string().optional(),
  caminha_sozinho: z.boolean().default(true),
  cadeirante: z.boolean().default(false),
  tempo_cadeirante: z.string().optional(),
  acamado: z.boolean().default(false),
  tempo_acamado: z.string().optional(),
  uso_aparelhos_locomocao: z.boolean().default(false),
  quais_aparelhos: z.string().optional(),
  risco_quedas: z.boolean().default(false),
  comunicativa: z.boolean().default(true),
  agressiva: z.boolean().default(false),
  humor_instavel: z.string().min(1, "Campo obrigatório"),
});

export type PacienteFormValues = z.infer<typeof pacienteSchema>;