import { z } from "zod";

const requiredString = (fieldName: string) => z.string().min(1, {
  message: `${fieldName} é obrigatório`
});

export const pacienteSchema = z.object({
  // Campos obrigatórios
  id_user: z.number().min(1, { message: "ID do usuário é obrigatório" }),
  nome_completo: requiredString("Nome Completo"),
  rg: requiredString("RG"),
  cpf: requiredString("CPF"),
  data_nascimento: requiredString("Data de Nascimento"),

  // Idade é calculada, então pode ser opcional no schema de validação do form
  idade: z.number().optional(),

  // Demais campos como opcionais e/ou nulos
  data_avaliacao: z.string().optional().nullable(),
  naturalidade: z.string().optional().nullable(),
  religiao: z.string().optional().nullable(),
  praticante: z.boolean().optional().nullable(),
  profissao: z.string().optional().nullable(),
  escolaridade: z.string().optional().nullable(),
  estado_civil: z.string().optional().nullable(),
  orgao_expedidor: z.string().optional().nullable(),
  nome_pai: z.string().optional().nullable(),
  nome_mae: z.string().optional().nullable(),
  data_acolhimento: z.string().optional().nullable(),
  responsavel: z.string().optional().nullable(),
  telefone_responsavel: z.string().optional().nullable(),
  rg_responsavel: z.string().optional().nullable(),
  cpf_responsavel: z.string().optional().nullable(),
  endereco: z.string().optional().nullable(),
  contato_emergencia: z.string().optional().nullable(),
  acolhido_outra_instituicao: z.boolean().optional().nullable(),
  tempo_acolhimento_anterior: z.string().optional().nullable(),
  possui_convenio: z.boolean().optional().nullable(),
  nome_convenio: z.string().optional().nullable(),
  tipo_sanguineo: z.string().optional().nullable(),
  receituario_medico: z.string().optional().nullable(),
  carteira_vacinacao: z.boolean().optional().nullable(),
  situacao_vacinal: z.string().optional().nullable(),
  vacina_covid_1: z.string().optional().nullable(),
  vacina_covid_2: z.string().optional().nullable(),
  vacina_covid_3: z.string().optional().nullable(),
  vacina_covid_4: z.string().optional().nullable(),
  alergias_medicamentosas: z.boolean().optional().nullable(),
  quais_alergias: z.string().optional().nullable(),
  tabagista: z.boolean().optional().nullable(),
  etilista: z.boolean().optional().nullable(),
  protese_dentaria: z.boolean().optional().nullable(),
  utiliza_fraldas: z.boolean().optional().nullable(),
  orientacao_tempo: z.boolean().optional().nullable(),
  orientacao_espaco: z.boolean().optional().nullable(),
  medicamentos_uso: z.string().optional().nullable(),
  grau_dependencia: z.number().optional().nullable(),
  banho: z.string().optional().nullable(),
  vestir: z.string().optional().nullable(),
  banheiro: z.string().optional().nullable(),
  transferencia: z.string().optional().nullable(),
  continencia: z.string().optional().nullable(),
  alimentacao: z.string().optional().nullable(),
  preferencias: z.string().optional().nullable(),
  dificuldade_visual: z.boolean().optional().nullable(),
  usa_oculos: z.boolean().optional().nullable(),
  demencia: z.boolean().optional().nullable(),
  tipo_demencia: z.string().optional().nullable(),
  comunicacao_verbal: z.boolean().optional().nullable(),
  dificuldade_fala: z.boolean().optional().nullable(),
  dificuldade_auditiva: z.boolean().optional().nullable(),
  protese_auditiva: z.boolean().optional().nullable(),
  avc: z.boolean().optional().nullable(),
  tce: z.boolean().optional().nullable(),
  hipertensao: z.boolean().optional().nullable(),
  cardiopatias: z.boolean().optional().nullable(),
  quais_cardiopatias: z.string().optional().nullable(),
  hipotireoidismo: z.boolean().optional().nullable(),
  colesterol_alto: z.boolean().optional().nullable(),
  artrose: z.boolean().optional().nullable(),
  diabetes: z.boolean().optional().nullable(),
  tipo_diabetes: z.string().optional().nullable(),
  historico_cancer: z.boolean().optional().nullable(),
  tipo_cancer: z.string().optional().nullable(),
  osteoporose: z.boolean().optional().nullable(),
  fraturas: z.boolean().optional().nullable(),
  onde_fraturas: z.string().optional().nullable(),
  cirurgia: z.boolean().optional().nullable(),
  onde_cirurgia: z.string().optional().nullable(),
  depressao: z.boolean().optional().nullable(),
  outros_antecedentes: z.string().optional().nullable(),
  alimenta_sozinho: z.boolean().optional().nullable(),
  tipo_alimentacao: z.string().optional().nullable(),
  dificuldade_degluticao: z.boolean().optional().nullable(),
  engasgos: z.boolean().optional().nullable(),
  uso_sonda: z.boolean().optional().nullable(),
  tipo_sonda: z.string().optional().nullable(),
  alergia_alimento: z.boolean().optional().nullable(),
  qual_alimento: z.string().optional().nullable(),
  caminha_sozinho: z.boolean().optional().nullable(),
  cadeirante: z.boolean().optional().nullable(),
  tempo_cadeirante: z.string().optional().nullable(),
  acamado: z.boolean().optional().nullable(),
  tempo_acamado: z.string().optional().nullable(),
  uso_aparelhos_locomocao: z.boolean().optional().nullable(),
  quais_aparelhos: z.string().optional().nullable(),
  risco_quedas: z.boolean().optional().nullable(),
  comunicativa: z.boolean().optional().nullable(),
  agressiva: z.boolean().optional().nullable(),
  humor_instavel: z.string().optional().nullable(),
});

export type PacienteFormValues = z.infer<typeof pacienteSchema>;
